// Flag emojis mapping for country codes
export const countryFlags: { [key: string]: string } = {
  // North America
  us: "🇺🇸",
  ca: "🇨🇦",
  mx: "🇲🇽",

  // Europe
  gb: "🇬🇧",
  de: "🇩🇪",
  fr: "🇫🇷",
  it: "🇮🇹",
  es: "🇪🇸",
  pt: "🇵🇹",
  nl: "🇳🇱",
  be: "🇧🇪",
  ch: "🇨🇭",
  at: "🇦🇹",
  se: "🇸🇪",
  no: "🇳🇴",
  dk: "🇩🇰",
  fi: "🇫🇮",
  pl: "🇵🇱",
  cz: "🇨🇿",
  hu: "🇭🇺",
  ro: "🇷🇴",
  bg: "🇧🇬",
  hr: "🇭🇷",
  si: "🇸🇮",
  sk: "🇸🇰",
  lt: "🇱🇹",
  lv: "🇱🇻",
  ee: "🇪🇪",
  ie: "🇮🇪",
  gr: "🇬🇷",
  cy: "🇨🇾",
  mt: "🇲🇹",
  lu: "🇱🇺",

  // Asia
  jp: "🇯🇵",
  cn: "🇨🇳",
  kr: "🇰🇷",
  in: "🇮🇳",
  sg: "🇸🇬",
  hk: "🇭🇰",
  tw: "🇹🇼",
  th: "🇹🇭",
  id: "🇮🇩",
  ph: "🇵🇭",
  vn: "🇻🇳",
  my: "🇲🇾",
  pk: "🇵🇰",
  bd: "🇧🇩",
  lk: "🇱🇰",
  mm: "🇲🇲",
  kh: "🇰🇭",
  la: "🇱🇦",
  mn: "🇲🇳",
  kz: "🇰🇿",
  uz: "🇺🇿",
  kg: "🇰🇬",
  tj: "🇹🇯",
  tm: "🇹🇲",
  az: "🇦🇿",
  am: "🇦🇲",
  ge: "🇬🇪",
  md: "🇲🇩",
  by: "🇧🇾",
  ua: "🇺🇦",
  ru: "🇷🇺",
  il: "🇮🇱",
  ae: "🇦🇪",
  qa: "🇶🇦",
  sa: "🇸🇦",
  om: "🇴🇲",
  kw: "🇰🇼",
  bh: "🇧🇭",
  jo: "🇯🇴",
  lb: "🇱🇧",
  iq: "🇮🇶",
  ir: "🇮🇷",
  af: "🇦🇫",

  // South America
  br: "🇧🇷",
  ar: "🇦🇷",
  cl: "🇨🇱",
  co: "🇨🇴",
  pe: "🇵🇪",
  uy: "🇺🇾",
  py: "🇵🇾",
  bo: "🇧🇴",
  ec: "🇪🇨",
  ve: "🇻🇪",
  gy: "🇬🇾",
  sr: "🇸🇷",

  // Central America & Caribbean
  gt: "🇬🇹",
  hn: "🇭🇳",
  ni: "🇳🇮",
  cr: "🇨🇷",
  pa: "🇵🇦",
  sv: "🇸🇻",
  bz: "🇧🇿",
  jm: "🇯🇲",
  tt: "🇹🇹",
  bb: "🇧🇧",
  ag: "🇦🇬",
  aw: "🇦🇼",
  bq: "🇧🇶",
  cw: "🇨🇼",
  sx: "🇸🇽",

  // Oceania
  au: "🇦🇺",
  nz: "🇳🇿",
  fj: "🇫🇯",
  pg: "🇵🇬",
  nc: "🇳🇨",
  pf: "🇵🇫",

  // Africa
  za: "🇿🇦",
  eg: "🇪🇬",
  ma: "🇲🇦",
  ng: "🇳🇬",
  ke: "🇰🇪",
  gh: "🇬🇭",
  ug: "🇺🇬",
  tz: "🇹🇿",
  et: "🇪🇹",
  mw: "🇲🇼",
  zm: "🇿🇲",
  bw: "🇧🇼",
  sz: "🇸🇿",
  ls: "🇱🇸",
  na: "🇳🇦",

  // Default
  default: "🌐",
};

// Get flag emoji for country code
export const getCountryFlag = (countryCode: string): string => {
  const normalizedCode = countryCode.toLowerCase();
  return countryFlags[normalizedCode] || countryFlags.default;
};

// Get flag emoji for currency code (fallback mapping)
export const getCurrencyFlag = (currencyCode: string): string => {
  const currencyToCountry: { [key: string]: string } = {
    usd: "us",
    eur: "eu", // European Union
    gbp: "gb",
    jpy: "jp",
    cny: "cn",
    krw: "kr",
    inr: "in",
    brl: "br",
    cad: "ca",
    aud: "au",
    chf: "ch",
    sek: "se",
    nok: "no",
    dkk: "dk",
    pln: "pl",
    czk: "cz",
    huf: "hu",
    ron: "ro",
    bgn: "bg",
    hrk: "hr",
    rub: "ru",
    uah: "ua",
    hkd: "hk",
    sgd: "sg",
    myr: "my",
    thb: "th",
    idr: "id",
    php: "ph",
    vnd: "vn",
    mxn: "mx",
    ars: "ar",
    clp: "cl",
    cop: "co",
    pen: "pe",
    uyu: "uy",
    pyg: "py",
    bob: "bo",
    ecs: "ec",
    ves: "ve",
    gtq: "gt",
    hnl: "hn",
    nio: "ni",
    crc: "cr",
    pab: "pa",
    svc: "sv",
    bzd: "bz",
    jmd: "jm",
    ttd: "tt",
    bbd: "bb",
    xcd: "ag", // Eastern Caribbean
    awg: "aw",
    ang: "bq", // Netherlands Antilles
    srd: "sr",
    gyd: "gy",
    fjd: "fj",
    nzd: "nz",
    zar: "za",
    egp: "eg",
    mad: "ma",
    ngn: "ng",
    kes: "ke",
    ghs: "gh",
    ugx: "ug",
    tzs: "tz",
    etb: "et",
    mwk: "mw",
    zmw: "zm",
    bwp: "bw",
    szl: "sz",
    lsl: "ls",
    nad: "na",
    mop: "mo",
    twd: "tw",
    ils: "il",
    aed: "ae",
    qar: "qa",
    sar: "sa",
    omr: "om",
    kwd: "kw",
    bhd: "bh",
    jod: "jo",
    lbp: "lb",
    iqd: "iq",
    irr: "ir",
    afn: "af",
    pkr: "pk",
    bdt: "bd",
    lkr: "lk",
    mmk: "mm",
    khr: "kh",
    lak: "la",
    mnt: "mn",
    kzt: "kz",
    uzs: "uz",
    kgs: "kg",
    tjs: "tj",
    tmt: "tm",
    azn: "az",
    amd: "am",
    gel: "ge",
    mdl: "md",
    byn: "by",
  };

  const countryCode = currencyToCountry[currencyCode.toLowerCase()];
  return countryCode ? getCountryFlag(countryCode) : countryFlags.default;
};